packages:
  - docs
  - packages/**
  - '!packages/nuxi'
  - '!packages/test-utils'
  - playground
  - test/fixtures/*

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - rolldown
  - unrs-resolver
  - vue-demi
