name: docs

on:
  push:
    paths:
      - "docs/**"
    branches:
      - 3.x

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@babd69bc8d78e6cdece903dfdcfb72d4e1a4f00d
      - if: ${{ github.repository_owner == 'nuxt' && github.event_name == 'push' }}
        run: curl "${{ secrets.DOCS_WEBHOOK }}"
